#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint && yarn git-format-staged --formatter "prettier --stdin-filepath "{}""  "*.ts" "*.js" "*.tsx" "*.jsx" "*.json" "*.html" "*.md" "*.yml" "*.css" "*.scss"
