name: Checks

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'yarn.lock'
      - '.github/workflows/checks.yml'
  pull_request:
    paths:
      - 'packages/**'
      - 'yarn.lock'
      - '.github/workflows/checks.yml'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run format check
        run: yarn format:check

      - name: Run lint check
        run: yarn lint

      - name: Run type check
        run: yarn client type-check

      - name: Run build of universe/client
        run: yarn client build
